apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: meditrack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: patient-service
          image: oshara19/notification-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: EUREKA_SERVER_URL
              value: "http://eureka-service.meditrack.svc.cluster.local:8761/eureka/"
          imagePullPolicy: Always
      automountServiceAccountToken: false
