apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: meditrack
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP  # Exposes the service internally within the cluster
