server:
  port: 8083  # Unique port for NotificationService

spring:
  application:
    name: notification-service  # Unique name for each service
  datasource:
    url: jdbc:postgresql://localhost:5432/healthsync_db
    username: oshara
    password: Oshara@4ever
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
