apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-patient-to-eureka
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: patient-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: eureka-service
      ports:
        - protocol: TCP
          port: 8761