server:
  port: 8761  # Default port for Eureka Server

eureka:
  client:
    register-with-eureka: false  # Eureka server doesn’t need to register itself
    fetch-registry: false        # Eureka server doesn't need to fetch the registry
  instance:
    hostname: localhost          # Replace with actual hostname if deploying remotely

spring:
  application:
    name: eureka-server
