apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP  # Exposes the service internally within the cluster
