---
apiVersion: v1
kind: Namespace
metadata:
  name: meditrack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  namespace: meditrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: oshara19/eureka-service:latest
          ports:
            - containerPort: 8761
