server:
  port: 8082  # Unique port for PatientService

spring:
  application:
    name: appointment-service  # Unique name for each service
  datasource:
    url: jdbc:postgresql://healthsync-db.c9iem4ysyosp.eu-west-2.rds.amazonaws.com:5432/healthsync_db
    username: healthsync_admin
    password: Random1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service.meditrack.svc.cluster.local:8761/eureka/ # URL of Eureka server
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
