server:
  port: 8084  # Unique port for AggregatorService

spring:
  application:
    name: aggregator-service  # Unique name for each service
  datasource:
    url: jdbc:postgresql://localhost:5432/healthsync_db
    username: oshara
    password: Oshara@4ever
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of Eureka server
  instance:
    prefer-ip-address: true
