apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  namespace: meditrack
spec:
  selector:
    app: aggregator-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP  # Exposes the service internally within the cluster
