apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
        - name: patient-service
          image: oshara19/aggregator-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: EUREKA_SERVER_URL
              value: "http://eureka-service.default.svc.cluster.local:8761/eureka/"
          imagePullPolicy: Always
      automountServiceAccountToken: false
