name: PR Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - patient-service
          - aggregator-service
          - appointment-service
          - notification-service
          - EurekaServer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
      - name: Build with Maven
        run: mvn -f ${{ matrix.service }}/pom.xml clean install